# This is a sample build configuration for Ruby.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: xmlsolutions/docsite

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - JEKYLL_ENV=production bundle exec jekyll build -t
          - bundle exec htmlproofer ./_site --url-ignore "/#.*/"
  branches:
    master:
      - step:
          script:
            - JEKYLL_ENV=production bundle exec jekyll build -t  --config _config.yml
            #- bundle exec htmlproofer ./_site --url-ignore "/#.*/,/http://.*/,/https://.*/"
            - JEKYLL_ENV=production bundle exec jekyll build -t
            - git clone https://github.com/airelogic-dev/aireflow-doc.git
            - cp -r /opt/atlassian/pipelines/agent/build/_site/* aireflow-doc/
            - cd aireflow-doc
            - git config --global user.email "david.bond@airelogic.com"
            - git config --global user.name "David Bond"
            - git config --global push.default simple
            - git add --all
            - git commit -m "Website auto build on `date`"
            - git push https://$githubtoken@github.com/airelogic-dev/aireflow-doc.git

definitions:
  caches:
    bundler: ./vendor